const translations = {
    en: {
        welcome: "Welcome to Haiming Wang's Portfolio",
        description: "Aspiring UI/UX Designer with a background in Interaction Design, Marketing, and Hospitality...",
        learnMore: "Learn More",
        contact: "Contact",
        phone: "Phone: 647-939-2230",
        footer: "&copy; 2025 Haiming Wang. All Rights Reserved.",
        about: "About Me",
        aboutDescription: "Hi, I'm Haiming Wang (Jack). I'm an international student from China currently based in Toronto. I have professional experience in marketing and hospitality management and am pursuing a degree in Interaction Design at George Brown College.",
        profile: "Profile",
        profileDescription1: "Dedicated International Student | Aspiring Marketing Professional",
        profileDescription2: "Motivated and adaptable professional with international experience in marketing and hospitality...",
        education: "Education",
        education1: "George Brown College – Toronto, ON<br>Degree in Interaction Design (Expected January 2024)",
        education2: "VPC College – Toronto, ON<br>Degree in Hospitality Management (Completed December 2023)",
        education3: "KPU University – Richmond, BC<br>Botany Studies (2021)",
        experience: "Professional Experience",
        experience1: "Marketing & UX Intern – FUCCBOI Studio | Wuhan, China<br>May 2019 – February 2020",
        experience1Details1: "Assisted in launching digital campaigns and improving <strong>user engagement</strong>.",
        experience1Details2: "Created marketing content and collaborated on branding strategies.",
        experience2: "Marketing Intern – Yong-Li-fu Studio | Shandong, China<br>September 2017 – January 2019",
        experience2Details1: "Conducted market research and supported UX-related marketing efforts.",
        experience2Details2: "Worked with cross-functional teams on user acquisition strategies.",
        experience3: "Customer Experience & Service Roles<br>2019 – 2023",
        experience3Details1: "Developed strong <strong>user empathy and problem-solving skills</strong> through direct customer interactions.",
        experience3Details2: "Gained real-world experience in optimizing service workflows for better user satisfaction.",
        skills: "Skills",
        skills1: "UX/UI Design: Wireframing, Prototyping, Visual Design, User Flows",
        skills2: "User Research & Testing: Usability Testing, A/B Testing, Heuristic Evaluation",
        skills3: "Tools & Software: Figma, Adobe XD, Photoshop, Illustrator, After Effects, HTML/CSS/Java (basic)",
        skills4: "Additional Skills: Digital Marketing Strategies, Brand & Product Development, User Interface, Cross-Cultural Communication",
        additionalInfo: "Additional Information",
        additionalInfo1: "Languages: English (Fluent), Mandarin (Native)",
        additionalInfo2: "Interests: Interaction Design, Marketing Innovations, Culinary Arts",
    },
    zh: {
        welcome: "欢迎来到王海铭的作品集",
        description: "具有交互设计、市场营销和酒店管理背景的UI/UX设计师...",
        learnMore: "了解更多",
        contact: "联系",
        phone: "电话: 647-939-2230",
        footer: "&copy; 2025 王海铭. 版权所有。",
        about: "关于我",
        aboutDescription: "你好，我是王海铭 (Jack)。我是一名来自中国的国际学生，目前居住在多伦多。我在市场营销和酒店管理方面有专业经验，目前正在乔治布朗学院攻读交互设计学位。",
        profile: "简介",
        profileDescription1: "敬业的国际学生 | 有抱负的市场营销专业人士",
        profileDescription2: "具有国际市场营销和酒店管理经验的专业人士...",
        education: "教育背景",
        education1: "乔治布朗学院 – 多伦多, ON<br>交互设计学位 (预计 2024年1月)",
        education2: "VPC学院 – 多伦多, ON<br>酒店管理学位 (完成于 2023年12月)",
        education3: "KPU大学 – 里士满, BC<br>植物学研究 (2021年)",
        experience: "专业经验",
        experience1: "市场营销与用户体验实习生 – FUCCBOI Studio | 中国武汉<br>2019年5月 – 2020年2月",
        experience1Details1: "协助启动数字营销活动并提高<strong>用户参与度</strong>。",
        experience1Details2: "创建营销内容并协作制定品牌策略。",
        experience2: "市场营销实习生 – 永立福工作室 | 中国山东<br>2017年9月 – 2019年1月",
        experience2Details1: "进行市场调研并支持与用户体验相关的营销工作。",
        experience2Details2: "与跨职能团队合作制定用户获取策略。",
        experience3: "客户体验与服务角色<br>2019年 – 2023年",
        experience3Details1: "通过直接的客户互动培养了<strong>用户同理心和问题解决能力</strong>。",
        experience3Details2: "在优化服务工作流程以提高用户满意度方面获得了实际经验。",
        skills: "技能",
        skills1: "UX/UI设计：线框图、原型设计、视觉设计、用户流程",
        skills2: "用户研究与测试：可用性测试、A/B测试、启发式评估",
        skills3: "工具与软件：Figma、Adobe XD、Photoshop、Illustrator、After Effects、HTML/CSS/Java（基础）",
        skills4: "其他技能：数字营销策略、品牌与产品开发、用户界面、跨文化沟通",
        additionalInfo: "附加信息",
        additionalInfo1: "语言：英语（流利），普通话（母语）",
        additionalInfo2: "兴趣：交互设计、营销创新、烹饪艺术",
    },
    fr: {
        welcome: "Bienvenue dans le portfolio de Haiming Wang",
        description: "Designer UI/UX en devenir avec une expérience en design d'interaction, marketing et hôtellerie...",
        learnMore: "En savoir plus",
        contact: "Contact",
        phone: "Téléphone : 647-939-2230",
        footer: "&copy; 2025 Haiming Wang. Tous droits réservés.",
        about: "À propos de moi",
        aboutDescription: "Bonjour, je suis Haiming Wang (Jack). Je suis un étudiant international originaire de Chine, actuellement basé à Toronto. J'ai une expérience professionnelle en marketing et gestion hôtelière et je poursuis un diplôme en design d'interaction au George Brown College.",
        profile: "Profil",
        profileDescription1: "Étudiant international dévoué | Professionnel du marketing en devenir",
        profileDescription2: "Professionnel motivé et adaptable avec une expérience internationale en marketing et hôtellerie...",
        education: "Éducation",
        education1: "George Brown College – Toronto, ON<br>Diplôme en design d'interaction (Prévu en janvier 2024)",
        education2: "VPC College – Toronto, ON<br>Diplôme en gestion hôtelière (Terminé en décembre 2023)",
        education3: "Université KPU – Richmond, BC<br>Études en botanique (2021)",
        experience: "Expérience professionnelle",
        experience1: "Stagiaire en marketing et UX – FUCCBOI Studio | Wuhan, Chine<br>Mai 2019 – Février 2020",
        experience1Details1: "A aidé au lancement de campagnes numériques et à l'amélioration de <strong>l'engagement utilisateur</strong>.",
        experience1Details2: "Créé du contenu marketing et collaboré sur des stratégies de marque.",
        experience2: "Stagiaire en marketing – Yong-Li-fu Studio | Shandong, Chine<br>Septembre 2017 – Janvier 2019",
        experience2Details1: "Effectué des recherches de marché et soutenu des efforts marketing liés à l'UX.",
        experience2Details2: "Travaillé avec des équipes interfonctionnelles sur des stratégies d'acquisition d'utilisateurs.",
        experience3: "Rôles en expérience client et service<br>2019 – 2023",
        experience3Details1: "Développé une forte <strong>empathie utilisateur et des compétences en résolution de problèmes</strong> grâce à des interactions directes avec les clients.",
        experience3Details2: "Acquis une expérience pratique dans l'optimisation des flux de travail pour une meilleure satisfaction des utilisateurs.",
        skills: "Compétences",
        skills1: "Design UX/UI : Wireframing, Prototypage, Design visuel, Flux utilisateur",
        skills2: "Recherche et tests utilisateur : Tests d'utilisabilité, Tests A/B, Évaluation heuristique",
        skills3: "Outils et logiciels : Unity, Figma, Adobe XD, Photoshop, Illustrator, After Effects, Github, HTML/CSS/Java (de base)",
        skills4: "Compétences supplémentaires : Stratégies de marketing numérique, Développement de marque et de produit, Interface utilisateur, Communication interculturelle",
        additionalInfo: "Informations supplémentaires",
        additionalInfo1: "Langues : Anglais (courant), Mandarin (natif)",
        additionalInfo2: "Intérêts : Design d'interaction, Innovations marketing, Arts culinaires",
    },
};

document.getElementById("languageSelector").addEventListener("change", (event) => {
    const selectedLanguage = event.target.value;
    document.querySelectorAll("[data-translate]").forEach((element) => {
        const key = element.getAttribute("data-translate");
        element.innerHTML = translations[selectedLanguage][key];
    });
});
